#!/bin/bash
#
# Generate HQC-128 test vectors from the Cryptol specification.
#
# These vectors use the same deterministic PRNG as the C reference and
# Ada/SPARK implementations: SHAKE256([0,1,...,47] || 0x00) producing
# seed_kem(32), m(16), salt(16).
#
# Output files (written to $OUTDIR):
#   cryptol_ti.txt  - intermediate values for cross-validation
#   cryptol_kat.txt - KAT entry (count=0) in standard format
#
# Usage:
#   ./gen_test_vectors.sh [OUTDIR]
#
# Default OUTDIR is the current directory.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CRYPTOL_MOD="Primitive/Asymmetric/KEM/HQC/Tests/HQC128.cry"
OUTDIR="${1:-.}"

cd "$SCRIPT_DIR/../../../.."  # cryptol-specs root

echo "Generating HQC-128 test vectors from Cryptol spec..."
echo "Working directory: $(pwd)"
echo "Output directory: $OUTDIR"

# Run all evaluations in a single Cryptol session
CRYPTOL_OUT=$(timeout 300 cryptol 2>&1 <<'CRYPTOL_EOF'
:l Primitive/Asymmetric/KEM/HQC/Tests/HQC128.cry
:set base=16
:set ascii=off

let (ek, dk) = KeyGen test_seed_kem
let (K, ct) = Encaps ek test_m test_salt
let ss = Decaps dk ct
let kem_stream = xof_bytes test_seed_kem

// Print values, one per line, prefixed with label
// Seeds
join test_seed_kem
join (take`{32} kem_stream)
join (take`{16} (drop`{32} kem_stream))
join test_seed_dk
join test_seed_ek
// KEM outputs
join ek
join dk
join ct
join K
join ss
// Encaps inputs
join test_m
join test_salt
// Hashes
join (Hash_H ek)
join (drop`{32} (Hash_G (Hash_H ek) test_m test_salt))
CRYPTOL_EOF
)

echo "Cryptol evaluation complete. Parsing output..."

# Extract hex values (lines containing 0x followed by hex digits)
mapfile -t HEXVALS < <(echo "$CRYPTOL_OUT" | grep -oP '0x[0-9a-f]+' | sed 's/^0x//')

if [ ${#HEXVALS[@]} -ne 14 ]; then
    echo "ERROR: Expected 14 hex values, got ${#HEXVALS[@]}" >&2
    echo "$CRYPTOL_OUT" | tail -20 >&2
    exit 1
fi

SEED_KEM="${HEXVALS[0]}"
SEED_PKE="${HEXVALS[1]}"
SIGMA="${HEXVALS[2]}"
SEED_DK="${HEXVALS[3]}"
SEED_EK="${HEXVALS[4]}"
EK="${HEXVALS[5]}"
DK="${HEXVALS[6]}"
CT="${HEXVALS[7]}"
K="${HEXVALS[8]}"
SS="${HEXVALS[9]}"
M="${HEXVALS[10]}"
SALT="${HEXVALS[11]}"
HASH_EK="${HEXVALS[12]}"
THETA="${HEXVALS[13]}"

echo "  seed_kem: ${SEED_KEM:0:20}... ($(( ${#SEED_KEM} / 2 )) bytes)"
echo "  ek:       ${EK:0:20}... ($(( ${#EK} / 2 )) bytes)"
echo "  ct:       ${CT:0:20}... ($(( ${#CT} / 2 )) bytes)"
echo "  K:        $K"
echo "  ss:       $SS"
echo "  K == ss:  $([ "$K" = "$SS" ] && echo YES || echo NO)"

# Write intermediate values file
cat > "$OUTDIR/cryptol_ti.txt" <<EOF
# HQC-1 Intermediate Values - Generated by Cryptol specification
# Cross-validation reference for Ada/SPARK implementation

### KEYGEN ###

seed_kem: $SEED_KEM

seed_pke: $SEED_PKE

sigma: $SIGMA

seed_dk: $SEED_DK

seed_ek: $SEED_EK

pk: $EK

sk: $DK


### ENCAPS ###

m: $M

salt: $SALT

hash_ek: $HASH_EK

theta: $THETA

ct: $CT

K: $K


### DECAPS ###

ss: $SS

# ss == K: $([ "$K" = "$SS" ] && echo True || echo False)
EOF

echo "Wrote $OUTDIR/cryptol_ti.txt"

# Write KAT file (count=0)
cat > "$OUTDIR/cryptol_kat.txt" <<EOF
# HQC-1 - Generated by Cryptol specification

count = 0
seed = ${SEED_KEM}${M}
pk = $EK
sk = $DK
ct = $CT
ss = $K
EOF

echo "Wrote $OUTDIR/cryptol_kat.txt"
echo "Done."
